build:

	 DOCKER_BUILDKIT=1 docker build  -t parrot-security .

exec:

	docker run -it -u root parrot-security bash

tag:

	docker tag parrot-security <your_docker_repo>

push:

	docker push <your_docker_repo>